// DO NOT EDIT THIS FILE! see README.TXT - Javascript Compressor 1.1.0
(function(){
tinymce.PluginManager.requireLangPack('concordion');
tinymce.create('tinymce.plugins.ConcordionPlugin',{
init:function(ed,url){
ed.addCommand('mceConcordion',function(){
ed.windowManager.open({
file:url+'/dialog.htm',
width:320+parseInt(ed.getLang('concordion.delta_width',0)),
height:120+parseInt(ed.getLang('concordion.delta_height',0)),
inline:1
},{
plugin_url:url,
some_custom_arg:'concordion arg'
});
});
ed.addButton('concordion',{
title:'concordion.desc',
cmd:'mceConcordion',
image:url+'/img/example.gif'
});
ed.onNodeChange.add(function(ed,cm,n){
cm.setActive('concordion',n.nodeName=='IMG');
});
},
createControl:function(n,cm){
return null;
},
getInfo:function(){
return{
longname:'Concordion plugin',
author:'Sebastien Guimont',
authorurl:'http://tinymce.moxiecode.com',
infourl:'http://wiki.moxiecode.com/index.php/TinyMCE:Plugins/concordion',
version:"1.0.0"
};
}
});
tinymce.PluginManager.add('concordion',tinymce.plugins.ConcordionPlugin);
})();
